/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DarkApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "LightApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PrimaryVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "SharedRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}